---
name: Hello world
"on": [pull_request_review]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Hello world
        uses: g4s8/hello-world-github-action@master
