---
name: Hello world
"on": [pull_request_review]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hello world
        uses: g4s8/hello-world-github-action@master
        with:
          env_test: 'hello-test'
          token: ${{ secrets.GITHUB_TOKEN }}
