---
name: rultor
"on":
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Overlay
        uses: g4s8/update-overlay-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
